### PR TITLE
Enhance debug output for retry strategies

### PR DESCRIPTION
**Pull request by Kiemes**
Retry strategies outputs the retryable type

[#129348495](https://www.pivotaltracker.com/story/show/129348495)

Signed-off-by: Beyhan Veli beyhan.veli@sap.com

### CODE REVIEW

**Comment by Kiemes** [comment]
Please update bosh-agent accordingly.

**Comment by voelzmo** [comment]
Some comments:
    * Please add some example output as a comment, so we can see what the new output looks like
    * why not use [%T](https://golang.org/pkg/fmt/) instead of reflect.TypeOf?

**Comment by Kiemes** [comment]
Example output before change: "Making attempt #0"
Example output after change: "Making attempt #0 for *retrystrategy_test.simpleRetryable"

**Comment by Kiemes** [comment]
When building the bosh-agent with the bumped utils, we figured out an issue with missing file. https://github.com/cloudfoundry/bosh-agent/blob/master/platform/dummy_platform.go#L63

This is addressed to the New York team which will reflect the changes of https://github.com/cloudfoundry/bosh-utils/commit/c75ddb6af8334a650c05dd8331b01d467c75e223 into the agent as well.

**Comment by Kiemes** [comment]
Building the bosh-agent works again. https://github.com/cloudfoundry/bosh-agent/commit/42386f9dcda5c1a297020cb8f7702f73346e9338 fixes the mentioned issue.

This PR is good to be merged again.

When trying to bump bosh-utils locally in the agent and running the integration tests we ran into a problem when Vagrant was rsyncing the sources. It complained broken link files from the vendored doublestar module. This might need some special attention when bumping bosh-utils after the merge of the pull request.

There seems to be a related fix in the doublestar module: https://github.com/bmatcuk/doublestar/commit/0dc18b220d56c7fa133e614d6a089df0ed9a9ae2

**Pull request merged**
