### PR TITLE
Move across drives in Windows

### PR DESCRIPTION
**Pull request by Fydon**
As mentioned in #10 there is still a problem when using rename across drives in Windows. This error occurs when using `bosh-cli add-blobs`.

### CODE REVIEW

**Comment by cppforlife** [comment]
@fydon can you please add a windows specific mover_test.go

**Comment by Fydon** [comment]
@cppforlife Sure I can try. How would I go about doing this across two drives? I assume that these would need to be real, rather than fake_file_system?

**Comment by cppforlife** [comment]
@Fydon i think it will be fine to use fake file sys just like we do for other branches in this class: https://github.com/cloudfoundry/bosh-utils/blob/master/fileutil/mover_test.go#L48

**Comment by Fydon** [comment]
@cppforlife Sure. I copied that context and its tests and used the Windows specific error. Are those tests  correct?

**Pull request merged**
