### PR TITLE
Add username for socks5 url

### PR DESCRIPTION
**Pull request by voelzmo**
This PR depends on https://github.com/cloudfoundry/bosh-utils/pull/37

* NewSocks5Proxy now allows for passing in a logger, defaulting to `stdout`. Should we pass in some boshlogger instead?
* Now also pruning all test files from dependencies, removing even more from `vendor`

### CODE REVIEW

**Comment by cppforlife** [comment]
https://github.com/cloudfoundry/socks5-proxy/pull/7 introduced NewSocks5Proxy that takes a logger (that could be discardable logger). we can use cloudfoundry/socks5-proxy project instead of a custom fork.

**Comment by genevieve** [comment]
What custom fork of socks5-proxy are you referring to?

**Comment by genevieve** [comment]
Are you referring the go-socks5 fork?

**Comment by genevieve** [comment]
In the fork, we fixed logging for two error cases that would otherwise be swallowed and not returned or logged anywhere. https://github.com/genevieve/go-socks5/blob/54f73bdb8a8e85a6611d3d29ab9bbf98c2a060d7/socks5.go#L147-L159

**Comment by voelzmo** [comment]
Added new commit to pass in discarding logger rather than `nil`. If you agreed on whether having github.com/genevieve/go-socks5 fork in there as a transitive dependency, then I think this is good to go.

**Comment by voelzmo** [comment]
ping @cppforlife how do you feel about merging this in?

**Comment by genevieve** [comment]
The fork of go-socks5 has been moved to github.com/cloudfoundry/go-socks5.

**Comment by genevieve** [comment]
@voelzmo If you can update github.com/cloudfoundry/socks5-proxy one more time, it will reference the correct path for go-socks5 and this should be good.

**Comment by cppforlife** [comment]
much appreciated, @genevieve

**Comment by voelzmo** [comment]
@cppforlife @genevieve done. Everything should now come out of the cloudfoundry org.

**Comment by voelzmo** [comment]
merged master back in to get a clean diff for this PR

**Comment by genevieve** [comment]
Thanks Marco!

**Pull request merged**
