### PR TITLE
Attempt to make tar work on Windows

### PR DESCRIPTION
**Pull request by Fydon**
The `tar` commandline requires changes to the path for it to work on Windows. As a result I moved `CompressSpecificFilesInDir` and `DecompressFileToDir` into separate Windows and non Windows build files. I also split the tests into separate Windows and non Windows build files, so that they will be able to run build specific tests. All the tests in `fileutil` are passing on Windows.

I'm still new to Go, so please let me know how I can improve this.

As `tar` isn't available on Windows by default, so #9 is still advised, but these changes should enable the version of `tar` that comes with [Git][1] to work.

[1]: https://git-scm.com/

### CODE REVIEW

**Comment by charlievieth** [comment]
@Fydon Thanks for the PR.  This isn't documented (and probably should be), but we added Windows support to bosh-utils in order to support the bosh-agent, which includes a [BSD tar](https://github.com/cloudfoundry/bosh-agent/blob/master/integration/windows/fixtures/tar.exe) compiled for Windows (note: you will also need [zlib.dll](https://github.com/cloudfoundry/bosh-agent/blob/master/integration/windows/fixtures/zlib1.dll)).  I believe the source comes from [libarchive](https://github.com/libarchive/libarchive) - we have a [story](https://www.pivotaltracker.com/story/show/139296349) to start building tar in our CI.

We do not use the tar bundled with [Git](https://git-scm.com/downloads) as it does not work with Windows file paths and the Unix paths it accepts are not valid Windows paths.  It breaks interoperability with the Windows API and Go's standard library.  For example:

| Path | Windows API | BSD Tar | Git Tar |
| ---- | :------------- | :------- |  :------ |
| `/Windows/Temp/foo` | valid | valid | **invalid** |
| `/c/Windows/Temp/foo` | **invalid** | **invalid** | valid |
| `C:\Windows\Temp\foo` | valid | valid | **invalid** |

We cannot support one without breaking the other and supporting both would require deducing the version/flavor of tar at runtime, which is not viable.

I think the best solution is for us to improve the documentation around tar on Windows, build tar in our [CI](https://www.pivotaltracker.com/story/show/139296349) and make that tar publicly available (and pointed to in the bosh-utils and bosh-agent docs).

**Comment by charlievieth** [comment]
Closing as this PR makes bosh-utils dependent on the tar installed with [git-bash](https://git-scm.com/downloads) and breaks compatibility with cygwin-tar and libarchive-tar (which correctly handles Windows paths.

We created a story to document tar on Windows: [139998715](https://www.pivotaltracker.com/story/show/139998715).

**Comment by cppforlife** [comment]
i think we are not quite ready to close this PR. the reason why Fydon is making these changes is to make bosh-cli v2 work on windows (not on top of windows stemcells) which cannot rely on a specific tar being present. but you do bring a good point about bosh-utils also being used by the agent (which is good) which does run on a deterministic window image. so the question remains how do we get this to work on top of windows stemcells and arbitrary windows machines -- i think the answer to that is we need to use go std library to do the unpacking for windows impl (and possibly switch linux impl at some point as well).

**Comment by charlievieth** [comment]
Didn't realize this was related to the bosh-cli (it's mentioned in https://github.com/cloudfoundry/bosh-utils/issues/9, but not here).  

I would rather not re-open this PR as it would make the bosh-agent and bosh-cli dependent on the tar bundled with git-bash (GPL-2.0).  This would also likely break the bosh-cli for those using the popular cygwin terminal.  Maybe https://github.com/cloudfoundry/bosh-utils/issues/9 or the bosh-cli is a better place for this issue.
 
Using Go's `archive/tar` lib would be great, but the lib is spartan.  Maybe we could explore bundling the bsdtar provided by [libarchive](https://github.com/libarchive/libarchive) with the bosh-cli or bosh-utils.

**Comment by Fydon** [comment]
How about using [archiver]?

[1]: https://github.com/cloudfoundry/archiver

**Comment by jaresty** [comment]
Merge story [#152974592](https://www.pivotaltracker.com/story/show/152974592)

**Pull request closed without merging**
