### PR TITLE
Add `Get` methods to HTTP `RetryClient` for convenience

### PR DESCRIPTION
**Pull request by Kiemes**
We plan to use those methods in multiple places in bosh-agent.
Please merge and bump in bosh-agent.
We don't have write permissions for this repository, so we could not do it ourselves.

[#135338075](https://www.pivotaltracker.com/story/show/135338075)

Signed-off-by: Tom Kiemes <tom.kiemes@sap.com>

### CODE REVIEW

**Comment by cppforlife** [comment]
should use GetCustomized instead: https://github.com/cloudfoundry/bosh-utils/blob/master/httpclient/http_client.go

**Comment by Kiemes** [comment]
This is just about extending the RetryClient, not creating it. The RetryClient does multiple `client.Do`s under the hood if necessary. We don't see, how this could be done in `GetCustomized`. We extract our new method from [bosh-agent](https://github.com/cloudfoundry/bosh-agent/blob/master/infrastructure/http_metadata_service.go#L269-L287) and make it available in bosh-utils to reuse it properly.

**Comment by beyhan** [comment]
Please have a look at the referenced PR https://github.com/cloudfoundry/bosh-agent/pull/117. 
It shows how this change makes the use of RetryClient more conveniently and can be consumed form different locations in bosh-agent.

**Comment by cppforlife** [comment]
@Kiemes to elaborate:

```go
type HTTPClient interface {
  GetCustomized(endpoint string, f func(*http.Request)) (*http.Response, error)
}
```

GetCustomized can be used with following setHeader as an example:

```go
setHeaders := func(req *http.Request) {
  req.Header.Add("Content-Type", "application/json")
}
```

To get HTTPClient you'll need to do something like this:

```go
... = NewHTTPClient(NewRetryClient(boshhttpclient.CreateDefaultClient(), ...))
```

**Comment by friegger** [comment]
@cppforlife We applied your suggested changes in cloudfoundry/bosh-agent#117. Please have a look there. Closing this.

**Comment by cppforlife** [comment]
- lets call private var "client" since it doesnt matter what type of client it is
- you can use CreateDefaultClient(nil) and that uses system certs

**Comment by Kiemes** [comment]
Closing as https://github.com/cloudfoundry/bosh-agent/pull/117 supersedes this PR.

**Pull request closed without merging**
