### PR TITLE
add ReadFileWithRedact function to redact sensitive data in log output

### PR DESCRIPTION
**Pull request by gu-bin**

### CODE REVIEW

**Comment by gu-bin** [comment]
This is for issue https://github.com/cloudfoundry/bosh-utils/issues/69

**Comment by aashah** [comment]
Hey @gu-bin,

The team took a look at this and we see the use-case that is being addressed here. However, we felt that the responsibility of redacting should be moved out to whoever is consuming bosh-utils. There is currently a way to prevent the file contents from being logged.

Does that sound reasonable?

Thanks,
aakash

**Comment by gu-bin** [comment]
Hi @aashah, thanks for the reply.
We do need to log the file content as there are other useful but not credential informations in it. If redact the file content before consuming bosh-utils, we need to create a new file with credentials redacted and pass the new file path to bosh-utils. Then bosh-utils will log the redacted file content but also return the redacted one to the caller which is not expected. The caller needs the actual file content without any redact. So we only want `fs.logger.DebugWithDetails` called in bosh-utils to take the redacted file content. Please consider the requirement. Thanks.

**Comment by aashah** [comment]
I do not fully understand your concerns, it's unclear why another file must be created as part of this workaround. I'm interested in hearing a clarification, but I'll also try to clarify my original response as well -

There is a flag in the existing `ReadFileWithOpts` (`ReadOpts.Quiet`) to prevent the file from being logged. Here's some psuedocode for what I'm describing:

```
content, err := bosh-utils-fs.ReadFileWithOpts("/some/path.txt", ReadOpts{Quiet: true})
redactedContent := redact(content)
myLogger.Info(redactedContent)
```

With this way, you can use the existing bosh-utils, redact the contents, and log them.

Can your problem be solved this way?

thanks
aakash

**Comment by MerricdeLauney** [comment]
@gu-bin Bumping to see if you had a chance to look over @aashah's comment. We're gonna close this PR for now, but please don't hesitate to re-open.

**Pull request closed without merging**
