### PR TITLE
Need to retry for 502 error

### PR DESCRIPTION
**Pull request by mattcui**
This PR is for addressing bosh issue [1926](https://github.com/cloudfoundry/bosh/issues/1926), ever discussed with @cppforlife and @maximilien , please help review. Thanks.

### CODE REVIEW

**Comment by mattcui** [comment]
@cppforlife could you please review the PR? Seems the travis has been hanging, Is there a way to re-launch it? Thanks.

/cc @maximilien

**Comment by bingosummer** [comment]
+1

**Comment by cppforlife** [comment]
we think `http.StatusBadGateway` might be safe to retry. 

will try to remove this one `http.StatusInternalServerError` and see if problems still happen.

**Comment by cppforlife** [comment]
@mattcui built cli binary locally and waiting for verification to happen.

**Comment by mattcui** [comment]
@cppforlife I removed retry for 500 error, only keep 502 error. Please help review and merge. Thanks.

**Pull request merged**
